### ISSUE TITLE
Make sure data updates every day

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/ds-floodexposure-monitoring-app#18]

**Comment by t-downing** [comment]
Should be addressed by https://github.com/OCHA-DAP/ds-floodexposure-monitoring/pull/5 (once `pipelines/update_database.py` is included in workflow `.yml`), provided app isn't caching exposure data and is just reading straight from db on the fly

**Comment by hannahker** [comment]
Closed as changes in https://github.com/OCHA-DAP/ds-floodexposure-monitoring have been merged!
