### ISSUE TITLE
Add return period and severity into summary

### ISSUE THREAD

**Issue by t-downing** [OCHA-DAP/ds-floodexposure-monitoring-app#25]
Adding some measure of severity in summary sentence, like "68,853 people exposed to flooding as of 2024-11-10. This is [higher than normal / normal / lower than normal], and historically happens on average every X years"

**Comment by hannahker** [comment]
@t-downing can I close this one with #36?

**Comment by t-downing** [comment]
> @t-downing can I close this one with #36?

Yup! Thought it was in the PR anyways, guess it didn't get auto-tagged
